### ISSUE TITLE
Fov is getting set in reverse

### ISSUE THREAD

**Issue by terpii** [superkooks/sot-fov#1]
Basically the program works fine, but when i start up with 120 fov set in the program, nothing changes. When i try to change it keeps setting it to 90. So i tried setting it to 140 fov, which decreased my in game fov. After setting it to 90 fov i got the desired effect.
Probably an issue with line 125 : binary.Write(instr, binary.LittleEndian, float32(120.0)/float32(fov)).

System info:
Linux arch 5.19.2-arch1-1
Steam with Proton 7.0-7.4
Steam launch options: gamemoderun %command%

**Comment by superkooks** [comment]
Sorry about that, when I made `fov` a constant I changed the wrong float. Should be fixed in the latest commit. Thanks for raising the issue!
